name = "blogging-app"
compatibility_date = "2023-12-01"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDE5NmQxY2UtZTk1Ni00ZTZkLWFiMTItMzk3NjJlYTEwNWM1IiwidGVuYW50X2lkIjoiNGQ3NWQzOTFiNWVjOGRmMGYwZDI0NmVjMTIxMGFhZDVhYmNkY2EwYzBlNzMxYzhiZTQxOTA2N2NkMzliNWIyNCIsImludGVybmFsX3NlY3JldCI6IjNiNTdjNzMxLTgwMTMtNDAwZS04MzI4LThkYmJmZTk3YzJhOCJ9.YAMysRnfF9-V_Hkd2CNkSkJXP_pTPdufVtckzxPpAlU"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
